import Head from 'next/head'
import axios from 'axios'
import { NextPage } from 'next'
import { Video } from 'types'
import VideoCard from '@/components/VideoCard'
import NoResults from '@/components/NoResults'
import { BASE_URL } from '@/utils'

interface Iprops {
  videos: Video[]
}


const  Home = ({ videos }: Iprops) => {
  console.log(videos);
  
  return (
    <>
      <Head>
        <title>tik tik</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col gap-10 videos h-full">
        {videos.length ? (
          videos.map((video: Video ) => (
            <VideoCard post={video} key={video._id}/>
          ))
        ) : (
          <NoResults text={'No videos'}/>
        )}
      </div>
    </>
  )
}

export const getServerSideProps = async () => {
  const {data} = await axios.get(`${BASE_URL}/api/post`)
  

  return { 
    props:{
      videos: data
    }
  }
}

export default Home
